server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: crm-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/crm/**

        - id: sales-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/sales/**

      default-filters:
        - AddResponseHeader=X-Gateway, SpringCloud

# Seguridad temporal para pruebas
spring.security.user:
  name: admin
  password: admin
